import { useEffect, useState } from 'react';
import { categoriesApi, suppliersApi } from '../api/resourcesApi';
import PageHeader from '../components/PageHeader';
import { Empty, ErrorState, Loading } from '../components/AsyncState';

const CatalogPage = () => { const [state, setState] = useState({ loading: true, error: '', categories: [], suppliers: [] }); const [category, setCategory] = useState(''); const [supplier, setSupplier] = useState({ name: '', email: '', phone: '' }); const [saving, setSaving] = useState(false);
  const load = () => { setState((current) => ({ ...current, loading: true, error: '' })); Promise.all([categoriesApi.list(), suppliersApi.list()]).then(([categories, suppliers]) => setState({ loading: false, error: '', categories: categories.data || [], suppliers: suppliers.data || [] })).catch(() => setState((current) => ({ ...current, loading: false, error: 'Unable to load catalog setup.' }))); }; useEffect(load, []);
  const addCategory = async (event) => { event.preventDefault(); if (category.trim().length < 2) return; setSaving(true); try { await categoriesApi.create({ name: category }); setCategory(''); load(); } catch (error) { setState((current) => ({ ...current, error: error.response?.data?.error?.message || 'Unable to add category.' })); } finally { setSaving(false); } };
  const addSupplier = async (event) => { event.preventDefault(); setSaving(true); try { await suppliersApi.create(supplier); setSupplier({ name: '', email: '', phone: '' }); load(); } catch (error) { setState((current) => ({ ...current, error: error.response?.data?.error?.message || 'Unable to add supplier.' })); } finally { setSaving(false); } };
  const remove = async (kind, id) => { try { await (kind === 'category' ? categoriesApi.remove(id) : suppliersApi.remove(id)); load(); } catch (error) { setState((current) => ({ ...current, error: error.response?.data?.error?.message || 'Unable to remove item.' })); } };
  if (state.loading) return <Loading />; return <><PageHeader eyebrow="Admin" title="Catalog setup" description="Maintain the reference data behind your inventory." />{state.error && <ErrorState message={state.error} onRetry={load} />}<section className="content-grid"><div className="panel"><div className="panel-heading"><h2>Categories</h2></div><form className="inline-form" onSubmit={addCategory}><input placeholder="Category name" value={category} onChange={(event) => setCategory(event.target.value)} /><button className="button" disabled={saving}>Add</button></form>{state.categories.length ? <div className="compact-list">{state.categories.map((item) => <div className="list-row" key={item._id}><strong>{item.name}</strong><button className="icon-button" title={`Delete ${item.name}`} onClick={() => remove('category', item._id)}>Delete</button></div>)}</div> : <Empty />}</div><div className="panel"><div className="panel-heading"><h2>Suppliers</h2></div><form className="stack-form" onSubmit={addSupplier}>{['name','email','phone'].map((field) => <input key={field} placeholder={field[0].toUpperCase() + field.slice(1)} type={field === 'email' ? 'email' : 'text'} value={supplier[field]} onChange={(event) => setSupplier((current) => ({ ...current, [field]: event.target.value }))} required />)}<button className="button" disabled={saving}>Add supplier</button></form>{state.suppliers.length ? <div className="compact-list">{state.suppliers.map((item) => <div className="list-row" key={item._id}><div><strong>{item.name}</strong><small>{item.email} · {item.phone}</small></div><button className="icon-button" title={`Delete ${item.name}`} onClick={() => remove('supplier', item._id)}>Delete</button></div>)}</div> : <Empty />}</div></section></>;
}; export default CatalogPage;
