import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { categoriesApi, productsApi, suppliersApi } from '../api/resourcesApi';
import PageHeader from '../components/PageHeader';
import { ErrorState, Loading } from '../components/AsyncState';

const blank = { sku: '', name: '', category: '', supplier: '', price: '', quantityInStock: 0, lowStockThreshold: 5 };
const ProductFormPage = () => { const { id } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState(blank); const [options, setOptions] = useState({ categories: [], suppliers: [] }); const [state, setState] = useState({ loading: Boolean(id), saving: false, error: '' });
  useEffect(() => { Promise.all([categoriesApi.list(), suppliersApi.list(), id ? productsApi.get(id) : Promise.resolve(null)]).then(([categories, suppliers, product]) => { setOptions({ categories: categories.data || [], suppliers: suppliers.data || [] }); if (product) setForm({ ...blank, ...product.data, category: product.data.category?._id || product.data.category, supplier: product.data.supplier?._id || product.data.supplier, price: product.data.price?.$numberDecimal || product.data.price }); setState((current) => ({ ...current, loading: false })); }).catch((error) => setState({ loading: false, saving: false, error: error.response?.data?.error?.message || 'Unable to load form.' })); }, [id]);
  const change = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); if (!form.sku.trim() || form.name.trim().length < 2 || !form.category || !form.supplier || Number(form.price) < 0 || Number(form.quantityInStock) < 0) { setState((current) => ({ ...current, error: 'Complete every field with a valid value.' })); return; } setState((current) => ({ ...current, saving: true, error: '' })); try { const payload = { ...form, price: Number(form.price), quantityInStock: Number(form.quantityInStock), lowStockThreshold: Number(form.lowStockThreshold) }; if (id) await productsApi.update(id, payload); else await productsApi.create(payload); navigate('/products'); } catch (error) { setState((current) => ({ ...current, saving: false, error: error.response?.data?.error?.message || 'Unable to save product.' })); } };
  if (state.loading) return <Loading />; return <><PageHeader eyebrow="Inventory" title={id ? 'Edit product' : 'Add product'} description="Keep catalog details precise so every sale is trustworthy." />{state.error && <ErrorState message={state.error} />}<form className="form-panel" onSubmit={submit}><div className="form-grid">{[['sku','SKU'],['name','Product name'],['price','Price'],['quantityInStock','Quantity in stock'],['lowStockThreshold','Low-stock threshold']].map(([name,label]) => <label key={name}>{label}<input name={name} type={name === 'price' ? 'number' : name === 'quantityInStock' || name === 'lowStockThreshold' ? 'number' : 'text'} min="0" step={name === 'price' ? '0.01' : '1'} value={form[name]} onChange={change} required /></label>)}<label>Category<select name="category" value={form.category} onChange={change} required><option value="">Select category</option>{options.categories.map((item) => <option value={item._id} key={item._id}>{item.name}</option>)}</select></label><label>Supplier<select name="supplier" value={form.supplier} onChange={change} required><option value="">Select supplier</option>{options.suppliers.map((item) => <option value={item._id} key={item._id}>{item.name}</option>)}</select></label></div><div className="form-actions"><button className="button button-ghost" type="button" onClick={() => navigate('/products')}>Cancel</button><button className="button" disabled={state.saving}>{state.saving ? 'Saving...' : 'Save product'}</button></div></form></>;
};
export default ProductFormPage;
